from homeassistant.const import CONF_SCAN_INTERVAL

DOMAIN = "mshokej"

CONF_TITLE = "title"
CONF_FAVORITE_TEAM = "favorite_team"
CONF_LIVE_POLL_INTERVAL = "live_poll_interval"
CONF_PRE_MATCH_BUFFER = "pre_match_buffer"
CONF_IDLE_POLL_INTERVAL = "idle_poll_interval"

DEFAULT_TITLE = "MS Hokej"
DEFAULT_FAVORITE_TEAM = "CZE"
DEFAULT_LIVE_POLL_INTERVAL = 60
DEFAULT_PRE_MATCH_BUFFER = 60
DEFAULT_IDLE_POLL_INTERVAL = 3600
DEFAULT_SCAN_INTERVAL = 1800

OPTIONS_KEYS = (
    CONF_TITLE,
    CONF_FAVORITE_TEAM,
    CONF_LIVE_POLL_INTERVAL,
    CONF_PRE_MATCH_BUFFER,
    CONF_IDLE_POLL_INTERVAL,
)

STORAGE_VERSION = 1
STORAGE_KEY_PREFIX = f"{DOMAIN}_results"

ATTR_SNAPSHOT = "snapshot"
ATTR_REFRESH_PLAN = "refresh_plan"
ATTR_LAST_UPDATE = "last_update"
ATTR_UPDATED_MATCHES = "updated_matches"
ATTR_WARNINGS = "warnings"
